BASE_FIELDS = [
    "{0}.identifier",
    "{0}.name",
    "text.plain as 'plain'",
    "text.html as 'html'",
    "aiod_entry.date_modified",
]

FILE_IS_GENERATED_COMMENT = """{0} This file has been generated by `generate_logstash_config.py`
{0} file, placed in `src/setup/logstash`
{0} -------------------------------------------------------------
"""

CONF_BASE = """http.host: "0.0.0.0"
xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.username: {0}
xpack.monitoring.elasticsearch.password: {1}
"""

INIT_INPUT_BASE = """  jdbc {{
    jdbc_driver_library => "/usr/share/logstash/mysql-connector-j.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://sqlserver:3306/aiod"
    jdbc_user => "{0}"
    jdbc_password => "{1}"
    clean_run => true
    record_last_run => false
    statement_filepath => "/usr/share/logstash/sql/init_{2}.sql"
    type => "{2}"
  }}
"""

SYNC_INPUT_BASE = """  jdbc {{
    jdbc_driver_library => "/usr/share/logstash/mysql-connector-j.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://sqlserver:3306/aiod"
    jdbc_user => "{0}"
    jdbc_password => "{1}"
    use_column_value => true
    tracking_column => "date_modified"
    tracking_column_type => "timestamp"
    schedule => "*/5 * * * * *"
    statement_filepath => "/usr/share/logstash/sql/sync_{2}.sql"
    type => "{2}"
  }}
  jdbc {{
    jdbc_driver_library => "/usr/share/logstash/mysql-connector-j.jar"
    jdbc_driver_class => "com.mysql.jdbc.Driver"
    jdbc_connection_string => "jdbc:mysql://sqlserver:3306/aiod"
    jdbc_user => "{0}"
    jdbc_password => "{1}"
    use_column_value => true
    tracking_column => "date_deleted"
    tracking_column_type => "timestamp"
    schedule => "*/5 * * * * *"
    statement_filepath => "/usr/share/logstash/sql/rm_{2}.sql"
    type => "rm_{2}"
  }}
"""

FILTER = """filter {
  mutate {
    remove_field => ["@version", "@timestamp"]
  }
}
"""

INIT_OUTPUT_BASE = """  if [type] == "{2}" {{
    elasticsearch {{
        hosts => "elasticsearch:9200"
        user => "{0}"
        password => "{1}"
        ecs_compatibility => disabled
        index => "{2}"
        document_id => "{2}_%{{identifier}}"
    }}
  }}
"""

SYNC_OUTPUT_BASE = """  if [type] == "{2}" {{
    elasticsearch {{
        hosts => "elasticsearch:9200"
        user => "{0}"
        password => "{1}"
        ecs_compatibility => disabled
        index => "{2}"
        document_id => "{2}_%{{identifier}}"
    }}
  }}
  if [type] == "rm_{2}" {{
    elasticsearch {{
        action => "delete"
        hosts => "elasticsearch:9200"
        user => "{0}"
        password => "{1}"
        ecs_compatibility => disabled
        index => "{2}"
        document_id => "{2}_%{{identifier}}"
    }}
  }}
"""

SQL_BASE = """SELECT {1}
FROM aiod.{0}
INNER JOIN aiod.aiod_entry ON aiod.{0}.aiod_entry_identifier=aiod.aiod_entry.identifier
LEFT JOIN aiod.text ON aiod.{0}.description_identifier=aiod.text.identifier{2}
"""

SQL_RM_BASE = """SELECT {0}.identifier
FROM aiod.{0}
WHERE aiod.{0}.date_deleted IS NOT NULL AND aiod.{0}.date_deleted > :sql_last_value
"""

INIT_CLAUSE = """
WHERE aiod.{0}.date_deleted IS NULL"""

SYNC_CLAUSE = """
WHERE aiod.{0}.date_deleted IS NULL AND aiod.aiod_entry.date_modified > :sql_last_value"""
