FILE_IS_GENERATED_COMMENT = """{{comment_tag}} This file has been generated by `generate_logstash_config_files.py`
{{comment_tag}} file, placed in `src/setup/logstash_setup`
{{comment_tag}} -------------------------------------------------------------------

"""
