#!/bin/bash

# Path to dirs
DIR_ROOT=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
DIR_DATA=$DIR_ROOT/data
DIR_MYSQL=$DIR_DATA/mysql
DIR_CONNECTORS=$DIR_DATA/connectors
DIR_DELETION=$DIR_DATA/deletion
DIR_ELASTIC=$DIR_DATA/elasticsearch
DIR_KEYCLOAK=$DIR_DATA/keycloak

# Path to the .env file
ENV_FILE="$DIR_ROOT/.env"
TOML_FILE="$DIR_ROOT/src/config.default.toml"
NGINX_CONF="$DIR_ROOT/nginx/default.conf"

#Profiles
PROFILES=("examples" "huggingface-datasets" "openml" "zenodo-datasets")

# Detect the operating system for compatibility with sed
OS=$(uname)

# Initialize list of services to start
SERVICES_TO_START=()

sedinplace() {
    local var=$1
    local newvar=$2
    local filename=$3
    if [[ "$OS" == "Darwin" ]]; then
    # macOS sed requires an extension for in-place editing (use empty string for no backup)
        sed -i '' "s/^${var}/${newvar}/" "$filename"
    else
        # Linux version of sed
        sed -i "s/^${var}/${newvar}/" "$filename"
    fi
}


# Function to read file and extract variable value
read_file() {
    local file_name=$1
    local var_name=$2
    local var_value=$(grep "^${var_name}=" "$file_name" | cut -d '=' -f2-)
    echo "$var_value"
}

# Function to update the variable in a  file
update_file() {
    local file_name=$1
    local var_name=$2
    local new_value=$3
    sedinplace "${var_name}=.*" "${var_name}=${new_value}" "$file_name"
}

generate_random_value() {
    echo "$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)"
}

configure_nginx() {
#to do: other cases: only nginx?
    if [[ " ${SERVICES_TO_START[@]} " =~ " app " ]]; then
        if ! grep -q "app" "$NGINX_CONF"; then
           sedinplace "#APP" "include conf.d\/includes\/app.conf;" "$NGINX_CONF"
        fi
    else
       if  grep -q "app" "$NGINX_CONF"; then
           sedinplace "include conf.d\/includes\/app.conf;" "#APP" "$NGINX_CONF"
       fi
    fi

    if [[ " ${SERVICES_TO_START[@]} " =~ " keycloak " ]]; then
        if ! grep -q "keycloak" "$NGINX_CONF"; then
            sedinplace "#KEYCLOAK" "include conf.d\/includes\/keycloak.conf;" "$NGINX_CONF"
        fi
    else
       sedinplace "include conf.d\/includes\/keycloak.conf;" "#KEYCLOAK" "$NGINX_CONF"
    fi
}

configure_service() {
    local service_name="$1"
    local docker_service_name="$2"
    local env_vars=("${@:3}")
    local value
    echo -n "Do you want to install $service_name [Y/n]?"
    [ -z "$AUTO_YES" ] && read -r value ||  echo "y";
    value=${value:-'Y'}
    if [[ $value =~ ^(Y|y|Yes|yes)$ ]]; then
       SERVICES_TO_START+=("$docker_service_name")
       for var in "${env_vars[@]}"; do
            current_value=$(read_file "$ENV_FILE" "$var")
           if [[ -z "$current_value" ]]; then
               current_value=$(generate_random_value)
           fi
           echo -n "$var ['$current_value']: "
           new_value=""
           [ -z ${AUTO_YES} ] && read -r new_value || echo "$current_value";
           new_value=${new_value:-$current_value}
           update_file "$ENV_FILE" "$var" "$new_value"
       done
       case "$docker_service_name" in
           app)
               echo "$docker_service_name extra configuration"
               ;;
           keycloak)
               echo "$docker_service_name extra configuration"
               ;;
           nginx)  
               echo "$docker_service_name extra configuration"
               configure_nginx
               ;;
           esac
    elif [[ $value =~ ^(N|n|No|no)$ ]]; then
       echo "To do: provide external service endpoint"
    else
       configure_service "$service_name" "$docker_service_name" "${env_vars[@]}"       
    fi

    
}    

start() {
    echo "Starting services"
    configure_service "AIoD Metadata Catalogue" "app" "AIOD_REST_PORT"
    configure_service "AIoD Login" "keycloak" "HOSTNAME" "KEYCLOAK_ADMIN_PASSWORD" "KEYCLOAK_CLIENT_SECRET" "AIOD_KEYCLOAK_PORT"
    configure_service "NGINX" "nginx" "AIOD_NGINX_PORT"
    # Build the docker compose command
    if [[ ${#SERVICES_TO_START[@]} -eq 0 ]]; then
        echo "No services selected. Exiting."
        exit 0
    fi
    if [ -z "$PROFILE" ]; then
       echo "Starting services: ${SERVICES_TO_START[*]} ..."
       docker compose up -d ${SERVICES_TO_START[@]}
    else
       echo "Starting ${PROFILE[@]}"
       docker compose ${PROFILE[@]} up -d
    fi
}

stop() {
    if [ -z $PROFILE ]; then
       echo "Stopping services: ${SERVICES_TO_START[@]} ..."
       docker compose down ${SERVICES_TO_START[@]}
    else
       echo "Stopping ${PROFILE[@]}"
       docker compose ${PROFILE[@]} down
    fi
}

clean() {
    if [ -z $PROFILE ]; then
       echo "Stopping services: ${SERVICES_TO_START[@]} ..."
       docker compose down ${SERVICES_TO_START[@]} -v
    else
       echo "Stopping ${PROFILE[@]}"
       docker compose ${PROFILE[@]} down -v
    fi
    echo -e "Please confirm to delete:\n$DIR_CONNECTORS\n$DIR_DELETION\n$DIR_MYSQL\n$DIR_ELASTIC\n$DIR_KEYCLOAK\n\n[Y/n]?\c"
    read -r value
    value=${value:-'Y'}
    if [[ $value =~ ^(Y|y|Yes|yes)$ ]]; then
        echo "Deleting ..."
        find $DIR_CONNECTORS -type f ! -name .gitkeep -delete
        find $DIR_DELETION -type f ! -name .gitkeep -delete
        rm -rf $DIR_MYSQL/*
        touch $DIR_MYSQL/.gitkeep
        rm -rf $DIR_ELASTIC/*
        rm -rf $DIR_KEYCLOAK/data/tmp
        rm -rf $DIR_KEYCLOAK/data/h2
        rm -rf $DIR_KEYCLOAK/data/transaction-logs
        touch $DIR_ELASTIC/.gitkeep
    fi
}

status() {
    echo "Checking application status"
    docker compose ls
}

logs() {
    echo "View logs from services (type Ctrl-C to exit)"
    docker compose logs $CMD_ARGS
}

display_usage() {
    cat <<EOF
 Usage: aiod [OPTIONS] COMMAND"

 Commands:
   start           Start the services
   stop            Stop the services
   clean           Stop and remove the services
   status          Check the status of services
   logs            View logs from services

 Options:
   -h, --help      Display this help message
   -f              Follow log output (type Ctrl-C to exit)
   -p, --profile   Add profile (${PROFILES[*]}) implies -y
   -y              Accept all default values
EOF
    exit
}

if [ $# -lt 1 ]
    then
    display_usage
fi

while [ -n "$1" ]; do
    case "$1" in
        -h|--help)
            display_usage
            exit 0
            ;;
        -y)
            AUTO_YES=true
            shift
            ;;
        -f)
            CMD_ARGS="-f"
            shift
            ;;
        -p| --profile)
            shift
            PROFILE+=("$1")
            shift
            ;;
        start)
            COMMAND="start"
            shift
            ;;
        stop)
            COMMAND="stop"
            shift
            ;;
        clean)
            COMMAND="clean"
            shift
            ;;
        status)
            COMMAND="status"
            shift
            ;;
        logs)
            COMMAND="logs"
            shift
            ;;
        -* | *)
            echo "Error: Invalid command or option '$1'"
            display_usage
            exit 1
            ;;
    esac
done

if [ -z $COMMAND ]; then
    echo "Error: No command provided"
    display_usage
    exit 1
fi

#Check profiles
for i in "${!PROFILE[@]}"; do
   var=${PROFILE[$i]}
   if [[ ! " ${PROFILES[@]} " =~ " $var " ]]; then
         echo "Error: Invalid profile $var"
         echo "Available profile are: ${PROFILES[*]}"
         display_usage
         exit 1
   else
     PROFILE[$i]="--profile ${PROFILE[$i]}"
     AUTO_YES=true
   fi
done

$COMMAND $CMD_ARGS
