-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT aiod_entry.date_modified, event.identifier, name, description_identifier, text.plain, text.html
FROM aiod.event
INNER JOIN aiod.aiod_entry ON aiod.event.aiod_entry_identifier=aiod.aiod_entry.identifier
LEFT JOIN aiod.text ON aiod.event.description_identifier=aiod.text.identifier
WHERE aiod.event.date_deleted IS NULL
