-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT aiod_entry.date_modified, ml_model.identifier, name, description_identifier, text.plain as 'plain', text.html as 'html'
FROM aiod.ml_model
INNER JOIN aiod.aiod_entry ON aiod.ml_model.aiod_entry_identifier=aiod.aiod_entry.identifier
LEFT JOIN aiod.text ON aiod.ml_model.description_identifier=aiod.text.identifier
WHERE aiod.ml_model.date_deleted IS NULL
