-- This file has been generated by `generate_logstash_config_files.py`
-- file, placed in `src/setup/logstash_setup`
-- -------------------------------------------------------------------
SELECT project.identifier, project.name, text.plain as 'plain', text.html as 'html', aiod_entry.date_modified 
FROM aiod.project
INNER JOIN aiod.aiod_entry ON aiod.project.aiod_entry_identifier=aiod.aiod_entry.identifier
LEFT JOIN aiod.text ON aiod.project.description_identifier=aiod.text.identifier
WHERE aiod.project.date_deleted IS NULL