-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT aiod_entry.date_modified, ml_model.identifier, name, description
FROM aiod.ml_model
INNER JOIN aiod.aiod_entry ON aiod.ml_model.aiod_entry_identifier=aiod.aiod_entry.identifier
WHERE aiod.ml_model.date_deleted IS NULL
