-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT aiod_entry.date_modified, publication.identifier, name, description_identifier, text.plain as 'plain', text.html as 'html', issn, isbn
FROM aiod.publication
INNER JOIN aiod.aiod_entry ON aiod.publication.aiod_entry_identifier=aiod.aiod_entry.identifier
LEFT JOIN aiod.text ON aiod.publication.description_identifier=aiod.text.identifier
WHERE aiod.publication.date_deleted IS NULL
