-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT aiod_entry.date_modified, project.identifier, name, description
FROM aiod.project
INNER JOIN aiod.aiod_entry ON aiod.project.aiod_entry_identifier=aiod.aiod_entry.identifier
WHERE aiod.project.date_deleted IS NULL
