-- This file has been generated by `generate_logstash_config_files.py`
-- file, placed in `src/setup/logstash_setup`
-- -------------------------------------------------------------------
SELECT organisation.identifier, organisation.name, text.plain as 'plain', text.html as 'html', aiod_entry.date_modified , legal_name
FROM aiod.organisation
INNER JOIN aiod.aiod_entry ON aiod.organisation.aiod_entry_identifier=aiod.aiod_entry.identifier
LEFT JOIN aiod.text ON aiod.organisation.description_identifier=aiod.text.identifier
WHERE aiod.organisation.date_deleted IS NULL