-- This file has been generated by `generate_logstash_config_files.py`
-- file, placed in `src/setup/logstash_setup`
-- -------------------------------------------------------------------
SELECT event.identifier
FROM aiod.event
WHERE aiod.event.date_deleted IS NOT NULL AND aiod.event.date_deleted > :sql_last_value