-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT event.identifier
FROM aiod.event
WHERE aiod.event.date_deleted IS NOT NULL AND aiod.event.date_deleted > :sql_last_value
