-- This file has been generated by `generate_logstash_config.py`
-- file, placed in `src/setup/logstash`
-- -------------------------------------------------------------
SELECT ml_model.identifier
FROM aiod.ml_model
WHERE aiod.ml_model.date_deleted IS NOT NULL AND aiod.ml_model.date_deleted > :sql_last_value
