-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT news.identifier
FROM aiod.news
WHERE aiod.news.date_deleted IS NOT NULL AND aiod.news.date_deleted > :sql_last_value
