-- This file has been generated by `generate_logstash_config_files.py`
-- file, placed in `src/setup/logstash_setup`
-- -------------------------------------------------------------------
SELECT news.identifier
FROM aiod.news
WHERE aiod.news.date_deleted IS NOT NULL AND aiod.news.date_deleted > :sql_last_value