-- This file has been generated by `generate_logstash_config.py`
-- file, placed in `src/setup/logstash`
-- -------------------------------------------------------------
SELECT organisation.identifier
FROM aiod.organisation
WHERE aiod.organisation.date_deleted IS NOT NULL AND aiod.organisation.date_deleted > :sql_last_value
