-- This file has been generated by `generate_logstash_config.py`
-- file, placed in `src/setup/logstash`
-- -------------------------------------------------------------
SELECT publication.identifier
FROM aiod.publication
WHERE aiod.publication.date_deleted IS NOT NULL AND aiod.publication.date_deleted > :sql_last_value
