-- This file has been generated by `generate_logstash_config_files.py`
-- file, placed in `src/setup/logstash_setup`
-- -------------------------------------------------------------------
SELECT project.identifier
FROM aiod.project
WHERE aiod.project.date_deleted IS NOT NULL AND aiod.project.date_deleted > :sql_last_value