-- This file has been generated by `generate_logstash_config_files.py`
-- file, placed in `src/setup/logstash_setup`
-- -------------------------------------------------------------------
SELECT service.identifier
FROM aiod.service
WHERE aiod.service.date_deleted IS NOT NULL AND aiod.service.date_deleted > :sql_last_value