-- This file has been generated by `generate_logstash_config.py`
-- file, placed in `src/setup/logstash`
-- -------------------------------------------------------------
SELECT service.identifier
FROM aiod.service
WHERE aiod.service.date_deleted IS NOT NULL AND aiod.service.date_deleted > :sql_last_value
