-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT service.identifier
FROM aiod.service
WHERE aiod.service.date_deleted IS NOT NULL AND aiod.service.date_deleted > :sql_last_value
