-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT aiod_entry.date_modified, news.identifier, name, description, headline, alternative_headline
FROM aiod.news
INNER JOIN aiod.aiod_entry ON aiod.news.aiod_entry_identifier=aiod.aiod_entry.identifier
WHERE aiod.news.date_deleted IS NULL AND aiod.aiod_entry.date_modified > :sql_last_value
