-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT aiod_entry.date_modified, organisation.identifier, name, description, legal_name
FROM aiod.organisation
INNER JOIN aiod.aiod_entry ON aiod.organisation.aiod_entry_identifier=aiod.aiod_entry.identifier
WHERE aiod.organisation.date_deleted IS NULL AND aiod.aiod_entry.date_modified > :sql_last_value
