-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT aiod_entry.date_modified, project.identifier, name, description_identifier, text.plain as 'plain', text.html as 'html'
FROM aiod.project
INNER JOIN aiod.aiod_entry ON aiod.project.aiod_entry_identifier=aiod.aiod_entry.identifier
LEFT JOIN aiod.text ON aiod.project.description_identifier=aiod.text.identifier
WHERE aiod.project.date_deleted IS NULL AND aiod.aiod_entry.date_modified > :sql_last_value
