-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT aiod_entry.date_modified, service.identifier, name, description_identifier, text.plain as 'plain', text.html as 'html', slogan
FROM aiod.service
INNER JOIN aiod.aiod_entry ON aiod.service.aiod_entry_identifier=aiod.aiod_entry.identifier
LEFT JOIN aiod.text ON aiod.service.description_identifier=aiod.text.identifier
WHERE aiod.service.date_deleted IS NULL AND aiod.aiod_entry.date_modified > :sql_last_value
