-- This file has been generated by `logstash_config.py` file
-- ---------------------------------------------------------
SELECT aiod_entry.date_modified, service.identifier, name, description, slogan
FROM aiod.service
INNER JOIN aiod.aiod_entry ON aiod.service.aiod_entry_identifier=aiod.aiod_entry.identifier
WHERE aiod.service.date_deleted IS NULL AND aiod.aiod_entry.date_modified > :sql_last_value
